from __future__ import annotations

import hashlib
import json
import os
from pathlib import Path

TEST_DATABASE_URL = os.environ.get("FLAVOURBENCH_TEST_DATABASE_URL")
if TEST_DATABASE_URL:
    os.environ["FLAVOURBENCH_DATABASE_URL"] = TEST_DATABASE_URL
    os.environ["FLAVOURBENCH_AUTO_CREATE_SCHEMA"] = "false"
else:
    TEST_DATABASE = Path(
        os.environ.get(
            "FLAVOURBENCH_TEST_DATABASE_PATH",
            f"/tmp/epicure-flavourbench-pytest-{os.getpid()}.sqlite3",
        )
    )
    TEST_DATABASE.unlink(missing_ok=True)
    os.environ["FLAVOURBENCH_DATABASE_URL"] = f"sqlite:///{TEST_DATABASE}"
    os.environ["FLAVOURBENCH_AUTO_CREATE_SCHEMA"] = "true"
os.environ["FLAVOURBENCH_EXECUTION_MODE"] = "mock"
os.environ["FLAVOURBENCH_SERVICE_TOKEN"] = "test-service-token"
os.environ["FLAVOURBENCH_ADMIN_TOKEN"] = "test-admin-token"
os.environ["FLAVOURBENCH_PSEUDONYM_SECRET"] = "test-pseudonym-secret"
os.environ["FLAVOURBENCH_TASK_VALIDATOR_IDENTITY_HMAC_SECRET"] = (
    "test-task-validator-identity-hmac-secret"
)
os.environ["FLAVOURBENCH_PUBLIC_ARENA_ENABLED"] = "true"
os.environ["FLAVOURBENCH_ADMISSION_MAX_BATTLES"] = "100"

# Consent is content-addressed in production.  Keep the test registry equally
# strict so route tests cannot pass against a digest with no reviewer-visible
# document behind it.
TEST_EXPERT_CONSENT_TEXT = (
    "# FlavourBench test reviewer consent\n\n"
    "Status: active\n\n"
    "Participation is voluntary and the exact pool is disclosed before review.\n"
)
TEST_EXPERT_CONSENT_SHA256 = hashlib.sha256(TEST_EXPERT_CONSENT_TEXT.encode("utf-8")).hexdigest()
TEST_EXPERT_CONSENT_DIRECTORY = Path(f"/tmp/epicure-flavourbench-pytest-consent-{os.getpid()}")
TEST_EXPERT_CONSENT_DIRECTORY.mkdir(mode=0o700, parents=True, exist_ok=True)
(TEST_EXPERT_CONSENT_DIRECTORY / f"{TEST_EXPERT_CONSENT_SHA256}.md").write_text(
    TEST_EXPERT_CONSENT_TEXT,
    encoding="utf-8",
)
os.environ["FLAVOURBENCH_ACTIVE_EXPERT_CONSENT_SHA256S"] = json.dumps([TEST_EXPERT_CONSENT_SHA256])
os.environ["FLAVOURBENCH_EXPERT_CONSENT_DOCUMENTS_DIR"] = str(TEST_EXPERT_CONSENT_DIRECTORY)

TEST_TASK_VALIDATION_PACKET_SHA256 = (
    "c45023aee6cf8ff91437c08c16ae20498b2d025e9a0155aedd44898de1d7fbb1"
)
TEST_TASK_VALIDATION_PACKET = (
    Path(__file__).resolve().parents[1]
    / "artifacts/season1/task-validity/human-validation-current-v2"
    / f"development-task-human-validation-v2-{TEST_TASK_VALIDATION_PACKET_SHA256}.json"
)
os.environ["FLAVOURBENCH_DEVELOPMENT_TASK_VALIDATION_PACKET_PATH"] = str(
    TEST_TASK_VALIDATION_PACKET
)
os.environ["FLAVOURBENCH_DEVELOPMENT_TASK_VALIDATION_PACKET_SHA256"] = (
    TEST_TASK_VALIDATION_PACKET_SHA256
)

TEST_TASK_VALIDATION_CAMPAIGN_DIR = (
    Path(__file__).resolve().parents[1] / "artifacts/season1/task-validation-campaign-v6"
)
TEST_TASK_ACQUISITION_DIR = (
    Path(__file__).resolve().parents[1] / "artifacts/season1/prospective-task-acquisition-v1"
)
TEST_TASK_VALIDATION_CAMPAIGN_SHA256 = (
    "76b248477b3adc81b6eb198666a93538534db8e945567e2a99fc69085f709709"
)
TEST_TASK_VALIDATION_ASSIGNMENT_SHA256 = (
    "631932c0560ec417e47ff4c3ea94814ca9c944253252d3f4adcee8bd595221f9"
)
TEST_TASK_VALIDATION_CANDIDATE_BUNDLE_SHA256 = (
    "b13ab30bfb391e57a24c81d0398dc98e408d88e5a0bf21c4e758bf9271724cc3"
)
TEST_TASK_VALIDATION_ACQUISITION_RECEIPT_SHA256 = (
    "847a95f7159ba778281fd5c20f0489a75f4655fc08a0de8075a0cba950259045"
)
TEST_TASK_VALIDATION_QUALITY_SHA256 = (
    "292492bce348a260eedf17b3cb04b041d4cc7c35aca47bc59bdf17d675a48ea8"
)
TEST_TASK_VALIDATION_READINESS_SHA256 = (
    "449df377dd8de515a46a80d36dffc80f1734f3e86a60a53651675fb75c9d82c0"
)
TEST_TASK_VALIDATION_AUTOMATED_REPLAY_SHA256 = (
    "89f6dede2826e27bcd69eb764e32bd7a203b371f0098831c78c1077383383157"
)
TEST_TASK_VALIDATION_AUTOMATED_REPLAY_PHYSICAL_SHA256 = (
    "ced66727597192342ddb978f7f48153a8fe82b0d5808d17f89c6ce42aabaaab9"
)
os.environ["FLAVOURBENCH_TASK_VALIDATION_CAMPAIGN_ENABLED"] = "true"
os.environ["FLAVOURBENCH_TASK_VALIDATION_SEASON_SLUG"] = "season-1"
os.environ["FLAVOURBENCH_TASK_VALIDATION_CAMPAIGN_PATH"] = str(
    TEST_TASK_VALIDATION_CAMPAIGN_DIR / f"campaign-{TEST_TASK_VALIDATION_CAMPAIGN_SHA256}.json"
)
os.environ["FLAVOURBENCH_TASK_VALIDATION_CAMPAIGN_SHA256"] = TEST_TASK_VALIDATION_CAMPAIGN_SHA256
os.environ["FLAVOURBENCH_TASK_VALIDATION_CANDIDATE_BUNDLE_PATH"] = str(
    TEST_TASK_ACQUISITION_DIR
    / f"public-human-task-candidates-{TEST_TASK_VALIDATION_CANDIDATE_BUNDLE_SHA256}.json"
)
os.environ["FLAVOURBENCH_TASK_VALIDATION_CANDIDATE_BUNDLE_SHA256"] = (
    TEST_TASK_VALIDATION_CANDIDATE_BUNDLE_SHA256
)
os.environ["FLAVOURBENCH_TASK_VALIDATION_ASSIGNMENT_PATH"] = str(
    TEST_TASK_ACQUISITION_DIR
    / f"public-human-task-review-assignment-{TEST_TASK_VALIDATION_ASSIGNMENT_SHA256}.json"
)
os.environ["FLAVOURBENCH_TASK_VALIDATION_ASSIGNMENT_SHA256"] = (
    TEST_TASK_VALIDATION_ASSIGNMENT_SHA256
)
os.environ["FLAVOURBENCH_TASK_VALIDATION_ACQUISITION_RECEIPT_PATH"] = str(
    TEST_TASK_ACQUISITION_DIR
    / f"public-api-acquisition-receipt-{TEST_TASK_VALIDATION_ACQUISITION_RECEIPT_SHA256}.json"
)
os.environ["FLAVOURBENCH_TASK_VALIDATION_ACQUISITION_RECEIPT_SHA256"] = (
    TEST_TASK_VALIDATION_ACQUISITION_RECEIPT_SHA256
)
os.environ["FLAVOURBENCH_TASK_VALIDATION_QUALITY_REPORT_PATH"] = str(
    TEST_TASK_VALIDATION_CAMPAIGN_DIR / f"quality-report-{TEST_TASK_VALIDATION_QUALITY_SHA256}.json"
)
os.environ["FLAVOURBENCH_TASK_VALIDATION_QUALITY_REPORT_SHA256"] = (
    TEST_TASK_VALIDATION_QUALITY_SHA256
)
os.environ["FLAVOURBENCH_TASK_VALIDATION_READINESS_PATH"] = str(
    TEST_TASK_VALIDATION_CAMPAIGN_DIR / f"readiness-{TEST_TASK_VALIDATION_READINESS_SHA256}.json"
)
os.environ["FLAVOURBENCH_TASK_VALIDATION_READINESS_SHA256"] = TEST_TASK_VALIDATION_READINESS_SHA256
os.environ["FLAVOURBENCH_TASK_VALIDATION_AUTOMATED_REPLAY_PATH"] = str(
    TEST_TASK_VALIDATION_CAMPAIGN_DIR
    / f"automated-replay-{TEST_TASK_VALIDATION_AUTOMATED_REPLAY_SHA256}.json"
)
os.environ["FLAVOURBENCH_TASK_VALIDATION_AUTOMATED_REPLAY_SHA256"] = (
    TEST_TASK_VALIDATION_AUTOMATED_REPLAY_SHA256
)
os.environ["FLAVOURBENCH_TASK_VALIDATION_AUTOMATED_REPLAY_PHYSICAL_SHA256"] = (
    TEST_TASK_VALIDATION_AUTOMATED_REPLAY_PHYSICAL_SHA256
)
