"""Create the isolated FlavourBench schema from a frozen baseline.

Revision ID: 0001_initial
Revises:
Create Date: 2026-07-15

This migration deliberately contains explicit DDL. Importing the live ORM here
would make the historical baseline change whenever application models change.
"""

from __future__ import annotations

import sqlalchemy as sa

from alembic import op

revision = "0001_initial"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        "seasons",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("slug", sa.String(length=80), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("official", sa.Boolean(), nullable=False),
        sa.Column("manifest_sha256", sa.String(length=64), nullable=False),
        sa.Column("prompt_registry_sha256", sa.String(length=64), nullable=False),
        sa.Column("tool_registry_sha256", sa.String(length=64), nullable=False),
        sa.Column("epicure_release_id", sa.String(length=160), nullable=False),
        sa.Column("epicure_bundle_sha256", sa.String(length=64), nullable=False),
        sa.Column("epicure_application_sha256", sa.String(length=64), nullable=False),
        sa.Column("budget_cap_micros", sa.BigInteger(), nullable=False),
        sa.Column("budget_used_micros", sa.BigInteger(), nullable=False),
        sa.Column("budget_reserved_micros", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("frozen_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "catalog_models",
        sa.Column("model_id", sa.String(length=200), nullable=False),
        sa.Column("canonical_slug", sa.String(length=240), nullable=False),
        sa.Column("name", sa.String(length=240), nullable=False),
        sa.Column("family", sa.String(length=120), nullable=False),
        sa.Column("open_weight", sa.Boolean(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("supports_tools", sa.Boolean(), nullable=False),
        sa.Column("supports_structured_outputs", sa.Boolean(), nullable=False),
        sa.Column("context_length", sa.Integer(), nullable=True),
        sa.Column("pricing_json", sa.JSON(), nullable=False),
        sa.Column("endpoint_json", sa.JSON(), nullable=False),
        sa.Column("discovered_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("retired_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("model_id"),
    )
    op.create_table(
        "expert_reviewers",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("reviewer_code", sa.String(length=80), nullable=False),
        sa.Column("invitation_sha256", sa.String(length=64), nullable=False),
        sa.Column("qualification_json", sa.JSON(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "incidents",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("severity", sa.String(length=24), nullable=False),
        sa.Column("code", sa.String(length=80), nullable=False),
        sa.Column("detail", sa.Text(), nullable=False),
        sa.Column("battle_id", sa.String(length=36), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "run_events",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("entity_type", sa.String(length=48), nullable=False),
        sa.Column("entity_id", sa.String(length=80), nullable=False),
        sa.Column("event_type", sa.String(length=80), nullable=False),
        sa.Column("payload_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "admission_events",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("pseudonym", sa.String(length=64), nullable=False),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("admitted", sa.Boolean(), nullable=False),
        sa.Column("reason", sa.String(length=120), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "season_models",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("season_id", sa.String(length=36), nullable=False),
        sa.Column("model_id", sa.String(length=200), nullable=False),
        sa.Column("slot_role", sa.String(length=48), nullable=False),
        sa.Column("provider_slug", sa.String(length=120), nullable=False),
        sa.Column("eligible", sa.Boolean(), nullable=False),
        sa.Column("manifest_sha256", sa.String(length=64), nullable=False),
        sa.Column("worst_case_cost_micros", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["model_id"], ["catalog_models.model_id"]),
        sa.ForeignKeyConstraint(["season_id"], ["seasons.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("season_id", "model_id"),
    )
    op.create_table(
        "tasks",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("public_id", sa.String(length=80), nullable=False),
        sa.Column("season_id", sa.String(length=36), nullable=False),
        sa.Column("family", sa.String(length=64), nullable=False),
        sa.Column("prompt", sa.Text(), nullable=False),
        sa.Column("prompt_sha256", sa.String(length=64), nullable=False),
        sa.Column("split", sa.String(length=24), nullable=False),
        sa.Column("review_status", sa.String(length=32), nullable=False),
        sa.Column("provenance_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["season_id"], ["seasons.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("season_id", "prompt_sha256"),
        sa.UniqueConstraint("season_id", "public_id"),
    )
    op.create_table(
        "battles",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("season_id", sa.String(length=36), nullable=False),
        sa.Column("track", sa.String(length=32), nullable=False),
        sa.Column("category", sa.String(length=64), nullable=False),
        sa.Column("prompt", sa.Text(), nullable=True),
        sa.Column("prompt_sha256", sa.String(length=64), nullable=False),
        sa.Column("client_nonce_sha256", sa.String(length=64), nullable=False),
        sa.Column("prompt_redacted", sa.Boolean(), nullable=False),
        sa.Column("research_consent", sa.Boolean(), nullable=False),
        sa.Column("release_review_status", sa.String(length=32), nullable=False),
        sa.Column("release_reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("requester_pseudonym", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("left_arm_id", sa.String(length=36), nullable=True),
        sa.Column("right_arm_id", sa.String(length=36), nullable=True),
        sa.Column("reserved_cost_micros", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("retention_until", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["season_id"], ["seasons.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "season_id",
            "requester_pseudonym",
            "client_nonce_sha256",
        ),
    )
    op.create_table(
        "response_arms",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("battle_id", sa.String(length=36), nullable=False),
        sa.Column("side", sa.String(length=8), nullable=False),
        sa.Column("condition", sa.String(length=32), nullable=False),
        sa.Column("model_id", sa.String(length=200), nullable=False),
        sa.Column("provider_slug", sa.String(length=120), nullable=False),
        sa.Column("actual_provider_slug", sa.String(length=160), nullable=True),
        sa.Column("actual_model_id", sa.String(length=240), nullable=True),
        sa.Column("generation_id", sa.String(length=160), nullable=True),
        sa.Column("provider_generation_ids_json", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("answer_markdown", sa.Text(), nullable=True),
        sa.Column("output_json", sa.JSON(), nullable=False),
        sa.Column("prompt_sha256", sa.String(length=64), nullable=False),
        sa.Column("system_prompt_sha256", sa.String(length=64), nullable=False),
        sa.Column("schema_sha256", sa.String(length=64), nullable=False),
        sa.Column("tool_schema_sha256", sa.String(length=64), nullable=False),
        sa.Column("decoding_json", sa.JSON(), nullable=False),
        sa.Column("epicure_release_id", sa.String(length=160), nullable=False),
        sa.Column("epicure_bundle_sha256", sa.String(length=64), nullable=False),
        sa.Column("epicure_application_sha256", sa.String(length=64), nullable=False),
        sa.Column("prompt_tokens", sa.Integer(), nullable=False),
        sa.Column("completion_tokens", sa.Integer(), nullable=False),
        sa.Column("reasoning_tokens", sa.Integer(), nullable=False),
        sa.Column("cost_micros", sa.BigInteger(), nullable=False),
        sa.Column("cost_reconciled", sa.Boolean(), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column("retries", sa.Integer(), nullable=False),
        sa.Column("finish_reason", sa.String(length=80), nullable=True),
        sa.Column("error_code", sa.String(length=120), nullable=True),
        sa.Column("error_detail", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["battle_id"], ["battles.id"]),
        sa.ForeignKeyConstraint(["model_id"], ["catalog_models.model_id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("battle_id", "side"),
    )
    op.create_table(
        "jobs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("kind", sa.String(length=48), nullable=False),
        sa.Column("battle_id", sa.String(length=36), nullable=True),
        sa.Column("payload_json", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("available_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("claimed_by", sa.String(length=120), nullable=True),
        sa.Column("claimed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["battle_id"], ["battles.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "votes",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("battle_id", sa.String(length=36), nullable=False),
        sa.Column("rater_pseudonym", sa.String(length=64), nullable=False),
        sa.Column("cohort", sa.String(length=24), nullable=False),
        sa.Column("choice", sa.String(length=24), nullable=False),
        sa.Column("reason_tags_json", sa.JSON(), nullable=False),
        sa.Column("rubric_json", sa.JSON(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=120), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["battle_id"], ["battles.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("battle_id", "rater_pseudonym", "cohort"),
        sa.UniqueConstraint("idempotency_key"),
    )
    op.create_table(
        "tool_calls",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("arm_id", sa.String(length=36), nullable=False),
        sa.Column("round_index", sa.Integer(), nullable=False),
        sa.Column("tool_name", sa.String(length=120), nullable=False),
        sa.Column("arguments_json", sa.JSON(), nullable=False),
        sa.Column("result_text", sa.Text(), nullable=False),
        sa.Column("result_sha256", sa.String(length=64), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column("is_error", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["arm_id"], ["response_arms.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "validator_results",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("arm_id", sa.String(length=36), nullable=False),
        sa.Column("validator_name", sa.String(length=120), nullable=False),
        sa.Column("validator_version", sa.String(length=48), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("score_milli", sa.Integer(), nullable=True),
        sa.Column("detail_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["arm_id"], ["response_arms.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "cost_events",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("season_id", sa.String(length=36), nullable=False),
        sa.Column("battle_id", sa.String(length=36), nullable=True),
        sa.Column("arm_id", sa.String(length=36), nullable=True),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("amount_micros", sa.BigInteger(), nullable=False),
        sa.Column("provider", sa.String(length=80), nullable=False),
        sa.Column("generation_id", sa.String(length=160), nullable=True),
        sa.Column("accounting_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["arm_id"], ["response_arms.id"]),
        sa.ForeignKeyConstraint(["battle_id"], ["battles.id"]),
        sa.ForeignKeyConstraint(["season_id"], ["seasons.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "leaderboard_snapshots",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("season_id", sa.String(length=36), nullable=False),
        sa.Column("track", sa.String(length=32), nullable=False),
        sa.Column("cohort", sa.String(length=24), nullable=False),
        sa.Column("category", sa.String(length=64), nullable=False),
        sa.Column("input_sha256", sa.String(length=64), nullable=False),
        sa.Column("payload_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["season_id"], ["seasons.id"]),
        sa.PrimaryKeyConstraint("id"),
    )

    indexes: dict[str, tuple[str, list[str], bool]] = {
        "ix_admission_events_action": ("admission_events", ["action"], False),
        "ix_admission_events_pseudonym": ("admission_events", ["pseudonym"], False),
        "ix_admission_lookup": (
            "admission_events",
            ["pseudonym", "action", "created_at"],
            False,
        ),
        "ix_battles_category": ("battles", ["category"], False),
        "ix_battles_client_nonce_sha256": ("battles", ["client_nonce_sha256"], False),
        "ix_battles_prompt_sha256": ("battles", ["prompt_sha256"], False),
        "ix_battles_release_review_status": (
            "battles",
            ["release_review_status"],
            False,
        ),
        "ix_battles_requester_pseudonym": ("battles", ["requester_pseudonym"], False),
        "ix_battles_season_id": ("battles", ["season_id"], False),
        "ix_battles_season_track_status": (
            "battles",
            ["season_id", "track", "status"],
            False,
        ),
        "ix_battles_status": ("battles", ["status"], False),
        "ix_battles_track": ("battles", ["track"], False),
        "ix_catalog_models_canonical_slug": (
            "catalog_models",
            ["canonical_slug"],
            False,
        ),
        "ix_catalog_models_status": ("catalog_models", ["status"], False),
        "ix_cost_events_season_id": ("cost_events", ["season_id"], False),
        "ix_expert_reviewers_active": ("expert_reviewers", ["active"], False),
        "ix_expert_reviewers_invitation_sha256": (
            "expert_reviewers",
            ["invitation_sha256"],
            True,
        ),
        "ix_expert_reviewers_reviewer_code": (
            "expert_reviewers",
            ["reviewer_code"],
            True,
        ),
        "ix_incidents_code": ("incidents", ["code"], False),
        "ix_incidents_severity": ("incidents", ["severity"], False),
        "ix_jobs_claim": ("jobs", ["status", "available_at", "created_at"], False),
        "ix_jobs_kind": ("jobs", ["kind"], False),
        "ix_jobs_status": ("jobs", ["status"], False),
        "ix_leaderboard_snapshots_cohort": (
            "leaderboard_snapshots",
            ["cohort"],
            False,
        ),
        "ix_leaderboard_snapshots_season_id": (
            "leaderboard_snapshots",
            ["season_id"],
            False,
        ),
        "ix_leaderboard_snapshots_track": (
            "leaderboard_snapshots",
            ["track"],
            False,
        ),
        "ix_response_arms_battle_id": ("response_arms", ["battle_id"], False),
        "ix_response_arms_condition": ("response_arms", ["condition"], False),
        "ix_response_arms_model_id": ("response_arms", ["model_id"], False),
        "ix_response_arms_status": ("response_arms", ["status"], False),
        "ix_run_events_entity_id": ("run_events", ["entity_id"], False),
        "ix_run_events_entity_type": ("run_events", ["entity_type"], False),
        "ix_run_events_event_type": ("run_events", ["event_type"], False),
        "ix_season_models_model_id": ("season_models", ["model_id"], False),
        "ix_season_models_season_id": ("season_models", ["season_id"], False),
        "ix_seasons_slug": ("seasons", ["slug"], True),
        "ix_seasons_status": ("seasons", ["status"], False),
        "ix_tasks_family": ("tasks", ["family"], False),
        "ix_tasks_prompt_sha256": ("tasks", ["prompt_sha256"], False),
        "ix_tasks_public_id": ("tasks", ["public_id"], False),
        "ix_tasks_season_id": ("tasks", ["season_id"], False),
        "ix_tool_calls_arm_id": ("tool_calls", ["arm_id"], False),
        "ix_validator_results_arm_id": ("validator_results", ["arm_id"], False),
        "ix_validator_results_status": ("validator_results", ["status"], False),
        "ix_validator_results_validator_name": (
            "validator_results",
            ["validator_name"],
            False,
        ),
        "ix_votes_battle_id": ("votes", ["battle_id"], False),
        "ix_votes_choice": ("votes", ["choice"], False),
        "ix_votes_cohort": ("votes", ["cohort"], False),
        "ix_votes_idempotency_key": ("votes", ["idempotency_key"], False),
        "ix_votes_rater_pseudonym": ("votes", ["rater_pseudonym"], False),
    }
    for name, (table, columns, unique) in indexes.items():
        op.create_index(name, table, columns, unique=unique)


def downgrade() -> None:
    for table in (
        "leaderboard_snapshots",
        "cost_events",
        "validator_results",
        "tool_calls",
        "votes",
        "jobs",
        "response_arms",
        "battles",
        "tasks",
        "season_models",
        "admission_events",
        "run_events",
        "incidents",
        "expert_reviewers",
        "catalog_models",
        "seasons",
    ):
        op.drop_table(table)
