"""Create the answered checklist without modifying the official NeurIPS template.

The official checklist questions and guidelines are copied byte-for-byte.  This script removes
only the marked instruction block and replaces the sixteen TODO answer/justification pairs in
their original order.  It fails closed if the upstream template shape changes.
"""

from __future__ import annotations

from pathlib import Path


ROOT = Path(__file__).resolve().parent
SOURCE = ROOT / "checklist.tex"
TARGET = ROOT / "checklist-answers.tex"

RESPONSES = [
    (
        r"\answerYes{}",
        "Sections~\\ref{sec:oracle}--\\ref{sec:discussion} state the benchmark contract, "
        "observed evidence, scoring rule, results, and scope.",
    ),
    (
        r"\answerYes{}",
        "Section~\\ref{sec:discussion} discusses construct, task coverage, route stability, "
        "reproducibility, and the intended interpretation of the score.",
    ),
    (
        r"\answerNA{}",
        "The paper introduces no theorem or formal theoretical result; the Wilson formula is a "
        "standard descriptive confidence interval.",
    ),
    (
        r"\answerYes{}",
        "Sections~\\ref{sec:design}--\\ref{sec:reproduction} specify the unit, success "
        "contract, ranking rule, exact inputs, and verification command for the central result.",
    ),
    (
        r"\answerYes{}",
        "The anonymous supplement includes the 32 generated prompts, complete 1,280-arm release, "
        "scoring code, vector tables and figures, and a standard-library verifier that "
        "reconstructs every reported rank offline.",
    ),
    (
        r"\answerYes{}",
        "Section~\\ref{sec:design} and Appendix~\\ref{app:routes} specify tasks, routes, paired "
        "arms, execution limits, failure handling, identities, and all ranked denominators.",
    ),
    (
        r"\answerYes{}",
        "Section~\\ref{sec:design} defines the two-sided 95\\% Wilson intervals and the table and "
        "Figure~\\ref{fig:forest} report exact counts and intervals.",
    ),
    (
        r"\answerNo{}",
        "Section~\\ref{sec:reproduction} records the local verification environment, but hosted model "
        "providers did not disclose inference hardware or energy use, preventing complete "
        "provider-side compute accounting.",
    ),
    (
        r"\answerYes{}",
        "The work uses paid provider endpoints and a generated task set without recruiting "
        "participants; Sections~\\ref{sec:discussion} and Limitations disclose safety, route "
        "stability, and interpretation risks.",
    ),
    (
        r"\answerYes{}",
        "The Discussion and Limitations sections cover missing-response scoring, leaderboard "
        "interpretation, task-set gaming, provider instability, and food-safety misuse.",
    ),
    (
        r"\answerNA{}",
        "The release contains no trained model, scraped-media dataset, or executable capability "
        "intended for harmful use; it contains bounded exact-choice responses and tool projections.",
    ),
    (
        r"\answerYes{}",
        "The manuscript credits providers and cited benchmark/software sources and documents its "
        "own CC BY 4.0 and third-party rights boundaries. All 32 prompts are generated by the released task compiler; "
        "raw provider credentials and unbounded tool payloads are omitted.",
    ),
    (
        r"\answerYes{}",
        "Section~\\ref{sec:reproduction} documents the aggregate, leaderboard, verifier, "
        "result hashes, and exact reproduction command.",
    ),
    (
        r"\answerNA{}",
        "No crowdsourcing or human-subject study was conducted. The tasks and answer keys are "
        "generated deterministically from the versioned Epicure runtime.",
    ),
    (
        r"\answerNA{}",
        "The reported automated study recruited no human participants and collected no human "
        "judgments; the reported score is computed entirely from executable traces and responses.",
    ),
    (
        r"\answerYes{}",
        "The evaluated LLM endpoints are the experimental subjects. Section~\\ref{sec:design} "
        "and Appendix~\\ref{app:routes} describe their paired role, tool exposure, routing, and "
        "failure handling.",
    ),
]


def main() -> None:
    source = SOURCE.read_text(encoding="utf-8")
    begin = "%%% BEGIN INSTRUCTIONS %%%"
    end = "%%% END INSTRUCTIONS %%%"
    if source.count(begin) != 1 or source.count(end) != 1:
        raise RuntimeError("official checklist instruction markers drifted")
    before, remainder = source.split(begin, 1)
    _, after = remainder.split(end, 1)
    rendered = before.rstrip() + "\n\n" + after.lstrip()

    answer_token = r"\answerTODO{}"
    justification_token = r"\justificationTODO{}"
    if rendered.count(answer_token) != len(RESPONSES):
        raise RuntimeError("official checklist answer count drifted")
    if rendered.count(justification_token) != len(RESPONSES):
        raise RuntimeError("official checklist justification count drifted")

    for answer, justification in RESPONSES:
        rendered = rendered.replace(answer_token, answer, 1)
        rendered = rendered.replace(justification_token, justification, 1)

    if answer_token in rendered or justification_token in rendered:
        raise RuntimeError("unanswered checklist item remains")
    TARGET.write_text(rendered, encoding="utf-8", newline="\n")


if __name__ == "__main__":
    main()
